config/routes.rb
Rails.application.routes.draw do
  root to: 'customers#index'

  resources :customers do
    resources :orders, only: %i[show] do
      patch 'paid'
      patch 'delivered'
    end
  end

  resource :cart, only: %i[show update] do
    get 'check_out', to: 'carts#check_out'
    post 'check_out', to: 'carts#confirm_check_out'
    delete 'line_item'
  end

  resources :orders, only: %i[index]

  resources :products
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart
  include ActiveModel::Model

  attr_accessor :product_ids, :amounts, :customer_id

  def initialize(attributes = {})
    super
    @product_ids ||= []
    @amounts ||= []
  end

  def self.from_session(session)
    if session[:cart]
      new(session[:cart])
    else
      new
    end
  end

  def add_line_item(product_id, amount)
    product_ids << product_id
    amounts << amount
  end

  def remove_line_item(index)
    product_ids.delete_at(index)
    amounts.delete_at(index)
  end

  def products
    product_ids.map do |product_id|
      Product.find(product_id)
    end
  end

  def empty?
    product_ids.none?
  end

  def check_out!
    order = Order.create(
      placed_at: Time.zone.now,
      customer_id: customer_id
    )

    product_ids.each.with_index do |product_id, index|
      LineItem.create(
        order: order,
        product_id: product_id,
        amount: amounts[index]
      )
    end
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :orders, dependent: :destroy

  validates :name, presence: true
  validates :email, presence: true
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :order
  belongs_to :product

  validates :amount, presence: true

  def price_cents
    product.price_cents * amount
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :line_items, dependent: :destroy

  def price_cents
    line_items.sum do |line_item|
      line_item.price_cents
    end
  end

  def paid?
    paid_at.present?
  end

  def delivered?
    delivered_at.present?
  end

  def paid!
    self.paid_at = Time.zone.now
  end

  def delivered!
    self.delivered_at = Time.zone.now
  end
end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :image, ProductImageUploader

  has_many :line_items, dependent: :destroy
  has_many :orders, through: :line_items
  has_many :customers, through: :orders

  validates :name, presence: true
  validates :price_cents, presence: true, numericality: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @cart = Cart.from_session(session)
  end

  def update
    product_id = params['cart']['product_id']
    amount = params['cart']['amount']

    if amount.to_i > 0
      @cart = Cart.from_session(session)
      @cart.add_line_item(product_id, amount)

      session[:cart] = @cart

      flash[:notice] = 'Product added to cart.'
    end

    redirect_to products_path
  end

  def check_out
    @cart = Cart.from_session(session)

    if @cart.empty?
      flash[:alert] = 'No products in cart.'

      redirect_to cart_path
    end
  end

  def confirm_check_out
    @cart = Cart.from_session(session)
    @cart.customer_id = params[:cart][:customer_id]
    @cart.check_out!

    flash[:notice] = 'Order created successfully.'
    session[:cart] = Cart.new

    redirect_to products_path
  end

  def line_item
    index = params['cart']['index'].to_i

    @cart = Cart.from_session(session)
    @cart.remove_line_item(index)

    redirect_to cart_path
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def index
    @customers = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def new
    @customer = Customer.new
  end

  def create
    @customer = Customer.new(customer_params)

    if @customer.save
      flash[:notice] = 'Customer successfully created.'
      redirect_to @customer
    else
      flash[:alert] = 'Error creating customer.'
      render :new
    end
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])

    if @customer.update(customer_params)
      redirect_to @customer
    else
      render :edit
    end
  end

  def destroy
    @customer = Customer.find(params[:id])

    if @customer.destroy
      flash[:notice] = 'Customer successfully deleted.'
    else
      flash[:alert] = 'Error deleting customer.'
    end

    redirect_to customers_path
  end

  private

  def customer_params
    params.require(:customer).permit(
      :name,
      :address,
      :zip_code,
      :city,
      :phone_number,
      :email
    )
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders = if params[:paid]
      Order.where.not(paid_at: nil)
    elsif params[:delivered]
      Order.where.not(delivered_at: nil)
    else
      Order.all
    end
  end

  def show
    customer = Customer.find(params[:customer_id])
    @order = customer.orders.find(params[:id])
  end

  def paid
    customer = Customer.find(params[:customer_id])
    @order = customer.orders.find(params[:order_id])

    @order.paid!

    if @order.save
      flash[:notice] = 'Order marked as paid.'
    else
      flash[:alert] = 'Error marking order as paid.'
    end

    redirect_to customer_order_path(customer, @order)
  end

  def delivered
    customer = Customer.find(params[:customer_id])
    @order = customer.orders.find(params[:order_id])

    @order.delivered!

    if @order.save
      flash[:notice] = 'Order marked as delivered.'
    else
      flash[:alert] = 'Error marking order as delivered.'
    end

    redirect_to customer_order_path(customer, @order)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @cart = Cart.from_session(session)
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      flash[:notice] = 'Product successfully created.'
      redirect_to @product
    else
      flash[:alert] = 'Error creating product.'
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])

    if @product.update(product_params)
      redirect_to @product
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])

    if @product.destroy
      flash[:notice] = 'Product successfully deleted.'
    else
      flash[:alert] = 'Error deleting product.'
    end

    redirect_to products_path
  end

  private

  def product_params
    params.require(:product).permit(
      :name,
      :description,
      :image,
      :price_cents
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def formatted_price_with_currency(price_cents)
    number_to_currency(price_cents / 100.0, unit: 'CHF', delimiter: "'", format: '%n %u')
  end

  def format_timestamp(timestamp)
    return if timestamp.nil?

    "#{distance_of_time_in_words(Time.now, timestamp)} ago (#{timestamp.strftime('%d.%m.%Y')})"
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
  def order_filters_active_class(filter)
    if filter == :all
      !params[:delivered] && !params[:paid]
    elsif filter == :delivered
      params[:delivered]
    elsif filter == :paid
      params[:paid]
    end ? 'active' : ''
  end
end

app/views/application/_form_errors.html.erb
<% if model.errors.any? %>
  <div class="form-errors">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li>
          <%= message %>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/carts/check_out.html.erb
<h1>Check out</h1>

<% if @cart.products.any? %>
  <ul>
    <% @cart.products.each do |product| %>
      <li>
        <%= product.name %>
      </li>
    <% end %>
  </ul>
<% else %>
  <p>No products in cart.</p>
<% end %>

<%= form_for @cart, url: check_out_cart_path, method: :post do |form| %>
  <%= form.collection_select :customer_id, Customer.all, :id, :name %>
  <%= form.submit 'Submit order' %>
<% end %>

app/views/carts/show.html.erb
<h1>Shopping cart</h1>

<% if @cart.products.any? %>
  <table>
    <thead>
      <th>Product</th>
      <th>Amount</th>
      <th></th>
    </thead>
    <tbody>
    <% @cart.products.each.with_index do |product, index| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= @cart.amounts[index] %></td>
        <td>
          <%= form_for @cart, url: line_item_cart_path, method: :delete do |form| %>
            <%= form.hidden_field :index, value: index %>
            <%= form.submit 'Delete' %>
          <% end %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% else %>
  <p>No products in cart.</p>
<% end %>

<%= link_to 'Check out', check_out_cart_path %>

app/views/customers/_form.html.erb
<%= render partial: 'form_errors', locals: { model: @customer } %>

<%= form_for @customer do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.label :address %><br>
    <%= form.text_field :address %>
  </p>

  <p>
    <%= form.label :zip_code %><br>
    <%= form.text_field :zip_code %>
  </p>

  <p>
    <%= form.label :city %><br>
    <%= form.text_field :city %>
  </p>

  <p>
    <%= form.label :phone_number %><br>
    <%= form.text_field :phone_number %>
  </p>

  <%= form.submit %>
<% end %>

app/views/customers/edit.html.erb
<h1>Edit Customer</h1>

<%= render 'form' %>

app/views/customers/index.html.erb
<h1>        
  <span class="oi" data-glyph="people"></span>
  Customers
</h1>

<table>
  <thead>
    <th>Name</th>
    <th></th>
    <th></th>
  </thead>
  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= link_to customer.name, customer %></td>
        <td>
          <%= link_to edit_customer_path(customer) do %>
            <span class="oi" data-glyph="pencil"></span>
            Edit
          <% end %>
        </td>
        <td>
          <%= link_to customer, data: {confirm: 'Are you sure?'}, method: :delete do %>
            <span class="oi" data-glyph="circle-x"></span>
            Delete
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to new_customer_path do %>
  <span class="oi" data-glyph="plus"></span>
  New customer
<% end %>

app/views/customers/new.html.erb
<h1>New Customer</h1>

<%= render 'form' %>

app/views/customers/show.html.erb
<h1><%= @customer.name %></h1>

<h2>Orders</h2>
<table>
  <thead>
    <th>Order #</th>
    <th>Amount</th>
    <th>Placed at</th>
    <th>Paid at</th>
    <th>Delivered at</th>
  </thead>
  <tbody>
    <% @customer.orders.each do |order| %>
      <tr>
        <td><%= link_to order.id, customer_order_path(@customer, order) %></td>
        <td><%= formatted_price_with_currency(order.price_cents) %></td>
        <td><%= format_timestamp(order.placed_at) %></td>
        <td><%= format_timestamp(order.paid_at) %></td>
        <td><%= format_timestamp(order.delivered_at) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<address>
  <%= @customer.name %><br>
  <%= @customer.address %><br>
  <%= @customer.zip_code %> <%= @customer.city %><br>
  Phone: <%= @customer.phone_number %>
</address>

<br>

<%= link_to 'Edit', edit_customer_path(@customer) %>
<%= link_to 'Delete', @customer, data: {confirm: 'Are you sure?'}, method: :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CustomerDatabase</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="navigation">
      <%= link_to customers_path do %>
        <span class="oi" data-glyph="people"></span>  
        Customers
      <% end %>
      <%= link_to orders_path do %>
        <span class="oi" data-glyph="document"></span>  
        Orders
      <% end %>
      <%= link_to products_path do %>
        <span class="oi" data-glyph="box"></span>  
        Products
      <% end %>
    </div>


    <div class="content">
      <% if flash[:notice] %>
        <div class="flash flash-notice"><%= flash[:notice] %></div>
      <% end %>
      <% if flash[:alert] %>
        <div class="flash flash-alert"><%= flash[:alert] %></div>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/orders/index.html.erb
<h1>
  <span class="oi" data-glyph="document"></span>  
  Orders
</h1>

<div class="order-filters">
  <div class="<%= order_filters_active_class(:all) %>">
    <%= link_to({}) do %>
      <span class="oi" data-glyph="infinity"></span>
      Show all orders
    <% end %>
  </div>

  <div class="<%= order_filters_active_class(:paid) %>">
    <%= link_to paid: true do %>
      <span class="oi" data-glyph="dollar"></span>
      Show paid orders
    <% end %>
  </div>

  <div class="<%= order_filters_active_class(:delivered) %>">
    <%= link_to delivered: true do %>
      <span class="oi" data-glyph="check"></span>
      Show delivered orders
    <% end %>
  </div>  
</div>

<table>
  <thead>
    <th>Order #</th>
    <th>Amount</th>
    <th>Customer</th>
    <th>Placed at</th>
    <th>Paid at</th>
    <th>Delivered at</th>
  </thead>
  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= link_to order.id, customer_order_path(order.customer, order) %></td>
        <td><%= formatted_price_with_currency(order.price_cents) %></td>
        <td><%= link_to order.customer.name, order.customer %></td>
        <td><%= format_timestamp(order.placed_at) %></td>
        <td><%= format_timestamp(order.paid_at) %></td>
        <td><%= format_timestamp(order.delivered_at) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/orders/show.html.erb
<h1>Order #<%= @order.id %></h1>

<p>
  Customer: <%= link_to @order.customer.name, @order.customer %>
</p>

<table>
  <thead>
    <th>Product</th>
    <th>Amount</th>
    <th>Price</th>
  </thead>
  <tbody>
    <% @order.line_items.each do |line_item| %>
      <tr>
        <td><%= link_to line_item.product.name, line_item.product %></td>
        <td><%= line_item.amount %></td>
        <td><%= formatted_price_with_currency(line_item.price_cents) %></td>
      </tr>
    <% end %>
  </tbody>
  <tfoot>
    <tr>
      <td>Total</td>
      <td></td>
      <td><%= formatted_price_with_currency(@order.price_cents) %></td>
    </tr>
  </tfoot>
</table>

<h2>Order placed</h2>
<p><%= format_timestamp(@order.placed_at) %></p>

<h2>Order paid</h2>
<% if @order.paid? %>
  <p><%= format_timestamp(@order.paid_at) %></p>
<% else %>
  Order not paid yet.
  <p>
    <%= link_to 'Paid', customer_order_paid_path(@order.customer, @order), method: :patch %>
  </p>
<% end %>

<h2>Order delivered</h2>
<% if @order.delivered? %>
  <p><%= format_timestamp(@order.delivered_at) %></p>
<% else %>
  Order not delivered yet.
  <% if @order.paid? %>
    <p>
      <%= link_to 'Delivered', customer_order_delivered_path(@order.customer, @order), method: :patch %>
    </p>
  <% end %>
<% end %>

app/views/products/_form.html.erb
<%= render partial: 'form_errors', locals: { model: @product } %>

<%= form_for @product, multipart: true do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </p>

  <p>
    <%= form.label :image %><br>
    <%= form.file_field :image %>
  </p>

  <p>
    <%= form.label :price_cents %><br>
    <%= form.number_field :price_cents, step: 1 %>
  </p>

  <%= form.submit %>
<% end %>

app/views/products/edit.html.erb
<h1>Edit Product</h1>

<%= render 'form' %>

app/views/products/index.html.erb
<p>
  <%= @cart.products.count %> products in 
  <%= link_to cart_path do %>
    <span class="oi" data-glyph="cart"></span>
    cart
  <% end %>
  .
</p>

<h1>
  <span class="oi" data-glyph="box"></span>  
  Products
</h1>

<table>
  <thead>
    <th></th>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td>
          <% if product.image.present? %>
            <%= link_to image_tag(product.image_url, width: 50), product %>
          <% end %>
        </td>
        <td><%= link_to product.name, product %></td>
        <td>
          <%= form_for @cart, url: cart_path, method: :patch do |form| %>
            <%= form.hidden_field :product_id, value: product.id %>
            <%= form.number_field :amount, value: 0, step: 1 %>
            <%= form.submit 'Add to cart' %>
          <% end %>
        </td>
        <td>
          <%= link_to edit_product_path(product) do %>
            <span class="oi" data-glyph="pencil"></span>
            Edit
          <% end %>
        </td>
        <td>
          <%= link_to product, data: {confirm: 'Are you sure?'}, method: :delete do %>
            <span class="oi" data-glyph="circle-x"></span>
            Delete
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to new_product_path do %>
  <span class="oi" data-glyph="plus"></span>
  New product
<% end %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

app/views/products/show.html.erb
<h1><%= @product.name %></h1>

<% if @product.image.present? %>
  <%= image_tag @product.image_url %>
<% end %>

<p>
  <%= @product.description %>
</p>

<p>
  <%= formatted_price_with_currency(@product.price_cents) %>
</p>


<strong>Customers who bought this product:</strong>
<ul>
  <% @product.customers.uniq.each do |customer| %>
    <li><%= link_to customer.name, customer %></li>
  <% end %>
</ul>

<%= link_to 'Edit', edit_product_path(@product) %>
<%= link_to 'Delete', @product, data: {confirm: 'Are you sure?'}, method: :delete %>